<?php

uses(RefreshDatabase::class);

test('show returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $category = \App\Models\Category::factory()->create();

    $response = $this->get(route('category.show', [$category]));

    $response->assertOk();
    $response->assertViewIs('frontend.category.show');
    $response->assertViewHas('category', $category);
    $response->assertViewHas('product');

    // TODO: perform additional assertions
});

// test cases...
