<?php

uses(RefreshDatabase::class);

test('edit returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $idea = \App\Models\Idea::factory()->create();

    $response = $this->get(route('idea.edit', [$idea]));

    $response->assertOk();
    $response->assertViewIs('frontend.idea.edit');
    $response->assertViewHas('idea', $idea);
    $response->assertViewHas('product');

    // TODO: perform additional assertions
});

test('show returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $idea = \App\Models\Idea::factory()->create();

    $response = $this->get(route('idea.show', [$idea]));

    $response->assertOk();
    $response->assertViewIs('frontend.idea.show');
    $response->assertViewHas('idea', $idea);
    $response->assertViewHas('product');

    // TODO: perform additional assertions
});

// test cases...
