<?php

test('index returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $response = $this->get(route('frontend.search.index'));

    $response->assertOk();
    $response->assertViewIs('frontend.search.index');
    $response->assertViewHas('keywords');

    // TODO: perform additional assertions
});

// test cases...
