version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    groups:
      composer-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
