<?php

uses(RefreshDatabase::class);

test('invoke returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $users = \App\Models\User::factory()->times(3)->create();

    $response = $this->getJson(route('api.users.index'));

    $response->assertOk();
    $response->assertJsonStructure([
        // TODO: compare expected response data
    ]);

    // TODO: perform additional assertions
});

// test cases...
