<?php

test('show returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $response = $this->get(route('file.attachments.show', ['action' => $action, 'media' => $media]));

    $response->assertOk();

    // TODO: perform additional assertions
});

test('show aborts with a 404', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    // TODO: perform additional setup to trigger `abort(404)`...

    $response = $this->get(route('file.attachments.show', ['action' => $action, 'media' => $media]));

    $response->assertNotFound();
});

// test cases...
