<?php

uses(RefreshDatabase::class);

test('index returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $response = $this->get(route('product.index'));

    $response->assertOk();
    $response->assertViewIs('frontend.product.index');

    // TODO: perform additional assertions
});

test('show returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $product = \App\Models\Product::factory()->create();

    $response = $this->get(route('product.show', [$product]));

    $response->assertOk();
    $response->assertViewIs('frontend.product.show');
    $response->assertViewHas('product', $product);

    // TODO: perform additional assertions
});

// test cases...
