<?php

uses(RefreshDatabase::class);

test('show returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $product = \App\Models\Product::factory()->create();

    $response = $this->get(route('product.progress', [$product]));

    $response->assertOk();
    $response->assertViewIs('frontend.product.progress');
    $response->assertViewHas('product', $product);

    // TODO: perform additional assertions
});

// test cases...
