<?php

uses(RefreshDatabase::class);

test('show returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $product = \App\Models\Product::factory()->create();
    $tag = \App\Models\Tag::factory()->create();

    $response = $this->get(route('product.tag', [$product, $tag]));

    $response->assertOk();
    $response->assertViewIs('frontend.product.tag');
    $response->assertViewHas('product', $product);
    $response->assertViewHas('tag', $tag);

    // TODO: perform additional assertions
});

// test cases...
