<?php

uses(RefreshDatabase::class);

test('show returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();

    $response = $this->get(route('user.viewprofile', [$user]));

    $response->assertOk();
    $response->assertViewIs('profile.view');
    $response->assertViewHas('user', $user);

    // TODO: perform additional assertions
});

// test cases...
