<?php

uses(RefreshDatabase::class);

test('index returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();

    $response = $this->post(route('user.loginas'), [
        // TODO: send request data
    ]);

    $response->assertRedirect($redirect);

    // TODO: perform additional assertions
});

// test cases...
