<?php

test('index returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $response = $this->get(route('admin.categories'));

    $response->assertOk();
    $response->assertViewIs('admin.categories');

    // TODO: perform additional assertions
});

// test cases...
