CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "password_resets" ("email" varchar not null, "token" varchar not null, "created_at" datetime);
CREATE INDEX "password_resets_email_index" on "password_resets" ("email");
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "created_at" datetime, "updated_at" datetime, "expires_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "teams" ("id" integer primary key autoincrement not null, "user_id" integer not null, "name" varchar not null, "personal_team" tinyint(1) not null, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "teams_user_id_index" on "teams" ("user_id");
CREATE TABLE IF NOT EXISTS "team_user" ("id" integer primary key autoincrement not null, "team_id" integer not null, "user_id" integer not null, "role" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "team_user_team_id_user_id_unique" on "team_user" ("team_id", "user_id");
CREATE TABLE IF NOT EXISTS "team_invitations" ("id" integer primary key autoincrement not null, "team_id" integer not null, "email" varchar not null, "role" varchar, "created_at" datetime, "updated_at" datetime, foreign key("team_id") references "teams"("id") on delete cascade);
CREATE UNIQUE INDEX "team_invitations_team_id_email_unique" on "team_invitations" ("team_id", "email");
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE TABLE IF NOT EXISTS "products" ("id" integer primary key autoincrement not null, "user_id" integer not null, "name" varchar not null, "description" text not null, "settings" text, "links" text, "slug" varchar not null, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"));
CREATE UNIQUE INDEX "products_slug_unique" on "products" ("slug");
CREATE TABLE IF NOT EXISTS "notifications" ("id" varchar not null, "type" varchar not null, "notifiable_type" varchar not null, "notifiable_id" integer not null, "data" text not null, "read_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE INDEX "notifications_notifiable_type_notifiable_id_index" on "notifications" ("notifiable_type", "notifiable_id");
CREATE TABLE IF NOT EXISTS "ideas" ("id" integer primary key autoincrement not null, "author_id" integer not null, "added_by" integer not null, "category_id" integer not null, "sticky_comment_id" integer, "title" varchar not null, "slug" varchar not null, "content" text not null, "status" varchar not null default 'considered', "business_value" integer not null default '0', "time_criticality" integer not null default '0', "complexity" integer not null default '0', "wsjf" numeric not null default '0', "use_case_id" varchar, "project_status" varchar not null default 'considered', "deleted_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("author_id") references "users"("id"), foreign key("added_by") references "users"("id"), foreign key("category_id") references "categories"("id") on delete cascade);
CREATE UNIQUE INDEX "ideas_slug_unique" on "ideas" ("slug");
CREATE TABLE IF NOT EXISTS "statuses" ("id" integer primary key autoincrement not null, "name" varchar not null, "slug" varchar not null, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime, "color" varchar);
CREATE UNIQUE INDEX "statuses_slug_unique" on "statuses" ("slug");
CREATE TABLE IF NOT EXISTS "votes" ("id" integer primary key autoincrement not null, "idea_id" integer not null, "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("idea_id") references "ideas"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade);
CREATE UNIQUE INDEX "votes_idea_id_user_id_unique" on "votes" ("idea_id", "user_id");
CREATE TABLE IF NOT EXISTS "comments" ("id" integer primary key autoincrement not null, "user_id" integer not null, "idea_id" integer not null, "content" text not null, "is_status_update" varchar not null default '', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"), foreign key("idea_id") references "ideas"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "file_attachments" ("id" integer primary key autoincrement not null, "user_id" integer not null, "item_id" integer not null, "client_file_name" varchar not null, "file_name" varchar not null, "section" varchar not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "media" ("id" integer primary key autoincrement not null, "model_type" varchar not null, "model_id" integer not null, "uuid" varchar, "collection_name" varchar not null, "name" varchar not null, "file_name" varchar not null, "mime_type" varchar, "disk" varchar not null, "conversions_disk" varchar, "size" integer not null, "manipulations" text not null, "custom_properties" text not null, "generated_conversions" text not null, "responsive_images" text not null, "order_column" integer, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "media_model_type_model_id_index" on "media" ("model_type", "model_id");
CREATE UNIQUE INDEX "media_uuid_unique" on "media" ("uuid");
CREATE TABLE IF NOT EXISTS "permissions" ("id" integer primary key autoincrement not null, "name" varchar not null, "guard_name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "permissions_name_guard_name_unique" on "permissions" ("name", "guard_name");
CREATE TABLE IF NOT EXISTS "roles" ("id" integer primary key autoincrement not null, "name" varchar not null, "guard_name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "roles_name_guard_name_unique" on "roles" ("name", "guard_name");
CREATE TABLE IF NOT EXISTS "model_has_permissions" ("permission_id" integer not null, "model_type" varchar not null, "model_id" integer not null, "created_at" datetime not null default CURRENT_TIMESTAMP, "updated_at" datetime not null default CURRENT_TIMESTAMP, foreign key("permission_id") references "permissions"("id") on delete cascade, primary key ("permission_id", "model_id", "model_type"));
CREATE INDEX "model_has_permissions_model_id_model_type_index" on "model_has_permissions" ("model_id", "model_type");
CREATE TABLE IF NOT EXISTS "model_has_roles" ("role_id" integer not null, "model_type" varchar not null, "model_id" integer not null, "created_at" datetime not null default CURRENT_TIMESTAMP, "updated_at" datetime not null default CURRENT_TIMESTAMP, foreign key("role_id") references "roles"("id") on delete cascade, primary key ("role_id", "model_id", "model_type"));
CREATE INDEX "model_has_roles_model_id_model_type_index" on "model_has_roles" ("model_id", "model_type");
CREATE TABLE IF NOT EXISTS "role_has_permissions" ("permission_id" integer not null, "role_id" integer not null, "created_at" datetime not null default CURRENT_TIMESTAMP, "updated_at" datetime not null default CURRENT_TIMESTAMP, foreign key("permission_id") references "permissions"("id") on delete cascade, foreign key("role_id") references "roles"("id") on delete cascade, primary key ("permission_id", "role_id"));
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar, "remember_token" varchar, "current_team_id" integer, "profile_photo_path" varchar, "created_at" datetime, "updated_at" datetime, "two_factor_secret" text, "two_factor_recovery_codes" text, "provider_user_id" varchar, "provider_token" text, "provider_platform" varchar, "banned_at" datetime);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "tag_groups" ("id" integer primary key autoincrement not null, "added_by" integer not null, "product_id" integer not null, "name" varchar not null, "slug" varchar not null, "is_managed" tinyint(1) not null, "admin_or_user" varchar check ("admin_or_user" in ('admin', 'user')) not null, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "tag_groups_slug_unique" on "tag_groups" ("slug");
CREATE TABLE IF NOT EXISTS "tags" ("id" integer primary key autoincrement not null, "tag_group_id" integer not null, "name" varchar not null, "slug" varchar not null, "added_by" varchar not null, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "tags_slug_unique" on "tags" ("slug");
CREATE TABLE IF NOT EXISTS "idea_tag" ("id" integer primary key autoincrement not null, "tag_id" integer not null, "idea_id" integer not null, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "idea_spam" ("id" integer primary key autoincrement not null, "idea_id" integer not null, "user_id" integer not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "comment_spam" ("id" integer primary key autoincrement not null, "comment_id" integer not null, "user_id" integer not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "categories" ("id" integer primary key autoincrement not null, "product_id" integer not null, "created_by" integer not null, "name" varchar not null, "description" text, "slug" varchar not null, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("created_by") references "users"("id") on delete no action on update no action, foreign key("product_id") references "products"("id") on delete cascade on update no action);
CREATE UNIQUE INDEX "categories_slug_unique" on "categories" ("slug");
CREATE TABLE IF NOT EXISTS "settings" ("id" integer primary key autoincrement not null, "group" varchar not null, "name" varchar not null, "locked" tinyint(1) not null default '0', "payload" text not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "settings_group_name_unique" on "settings" ("group", "name");
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2014_10_12_100000_create_password_resets_table',1);
INSERT INTO migrations VALUES(3,'2014_10_12_200000_add_two_factor_columns_to_users_table',1);
INSERT INTO migrations VALUES(4,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(5,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(6,'2020_05_21_100000_create_teams_table',1);
INSERT INTO migrations VALUES(7,'2020_05_21_200000_create_team_user_table',1);
INSERT INTO migrations VALUES(8,'2020_05_21_300000_create_team_invitations_table',1);
INSERT INTO migrations VALUES(9,'2021_10_13_091001_create_sessions_table',1);
INSERT INTO migrations VALUES(10,'2021_10_14_064804_create_products_table',1);
INSERT INTO migrations VALUES(11,'2021_10_14_083055_create_notifications_table',1);
INSERT INTO migrations VALUES(12,'2021_10_14_093644_create_categories_table',1);
INSERT INTO migrations VALUES(13,'2021_10_14_100649_create_ideas_table',1);
INSERT INTO migrations VALUES(14,'2021_10_18_092349_create_statuses_table',1);
INSERT INTO migrations VALUES(15,'2021_10_22_095635_create_votes_table',1);
INSERT INTO migrations VALUES(16,'2021_10_25_091308_create_comments_table',1);
INSERT INTO migrations VALUES(17,'2021_11_10_152209_create_file_attachments_table',1);
INSERT INTO migrations VALUES(18,'2021_11_16_132513_create_media_table',1);
INSERT INTO migrations VALUES(19,'2022_10_25_074958_create_permission_tables',1);
INSERT INTO migrations VALUES(20,'2022_11_04_090813_add_columns_to_users_table',1);
INSERT INTO migrations VALUES(21,'2022_11_04_151258_update_columns_to_users_table',1);
INSERT INTO migrations VALUES(22,'2022_11_11_145016_add_permissions_to_products',1);
INSERT INTO migrations VALUES(23,'2022_11_12_065117_update_categories_products_ideas_foreign_column',1);
INSERT INTO migrations VALUES(24,'2022_11_14_104445_add_timestamps_to_model_roles_permissions',1);
INSERT INTO migrations VALUES(25,'2022_11_21_150105_create_tables_tags_tags_group_tags_ideas',1);
INSERT INTO migrations VALUES(26,'2022_11_23_134945_update_table_tags_rename_a_column',1);
INSERT INTO migrations VALUES(27,'2022_11_24_095427_rename_tag_idea_table_to_tags_ideas',1);
INSERT INTO migrations VALUES(28,'2022_11_26_062241_rename_tags_ideas_table',1);
INSERT INTO migrations VALUES(29,'2022_11_30_144902_add_idea_spam_and_comment_spam_pivot_tables',1);
INSERT INTO migrations VALUES(30,'2022_12_02_102258_various_column_changes_before_old_data_migration',1);
INSERT INTO migrations VALUES(31,'2022_12_14_083707_create_settings_table',1);
INSERT INTO migrations VALUES(32,'2023_01_11_092655_create_general_settings',1);
INSERT INTO migrations VALUES(33,'2023_01_11_104610_create_azure_a_d_settings',1);
INSERT INTO migrations VALUES(34,'2023_01_12_084847_add_new_column_status_table',1);
INSERT INTO migrations VALUES(35,'2023_01_16_123330_rename_properties_azure_a_d_settings',1);
INSERT INTO migrations VALUES(36,'2023_02_06_110354_add_banned_at_to_users_table',1);
INSERT INTO migrations VALUES(37,'2023_03_15_130202_add_expired_at_column_to_personal_access_tokens_for_sanctum_3.x-upgrade',1);
INSERT INTO migrations VALUES(38,'2023_12_06_114140_create_links_settings',1);
INSERT INTO migrations VALUES(39,'2023_12_08_064649_add_divert_email_general_settings',1);
INSERT INTO migrations VALUES(40,'2023_12_18_141920_add_link_title_general_settings',1);
INSERT INTO migrations VALUES(41,'2023_12_20_085158_rename_s_m_t_puser',1);
INSERT INTO migrations VALUES(42,'2024_01_30_061115_alter_tables_to_enable_fulltext',1);
INSERT INTO migrations VALUES(43,'2024_03_27_074623_spatie_laravel_settings_v2to_v3',1);
